# Generated by Django 5.1.2 on 2024-10-09 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='overtime_policy',
            field=models.CharField(default='no_overtime', max_length=20),
        ),
        migrations.AddField(
            model_name='company',
            name='status_report_frequency',
            field=models.CharField(default='weekly', max_length=20),
        ),
        migrations.AddField(
            model_name='employee',
            name='productivity',
            field=models.IntegerField(default=100),
        ),
    ]
