# Generated by Django 5.1.2 on 2024-10-09 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_project_complexity'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='industry',
            field=models.CharField(choices=[('FINTECH', 'Fintech'), ('GAME_DEV', 'Game Development')], default='unset', max_length=20),
            preserve_default=False,
        ),
    ]
