# Generated by Django 5.1.2 on 2024-10-09 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_company_industry'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='game_status',
            field=models.CharField(choices=[('ONGOING', 'Ongoing'), ('WON', 'Won'), ('LOST', 'Lost')], default='ONGOING', max_length=10),
        ),
        migrations.AddField(
            model_name='company',
            name='revenue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='feature',
            name='state',
            field=models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('IN_PROGRESS', 'In Progress'), ('TESTING', 'Testing'), ('COMPLETED', 'Completed')], default='NOT_STARTED', max_length=20),
        ),
    ]
