# Generated by Django 5.1.2 on 2024-10-09 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_employee_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='bug',
            name='feature',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bugs', to='game.feature'),
        ),
    ]
