# Generated by Django 5.1.2 on 2024-10-10 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_bug_feature'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='funds_history',
            field=models.TextField(default='[]'),
        ),
        migrations.AddField(
            model_name='company',
            name='revenue_history',
            field=models.TextField(default='[]'),
        ),
    ]
