# Generated by Django 5.1.2 on 2024-10-12 04:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_company_funds_history_company_revenue_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='current_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
