# Generated by Django 5.1.2 on 2024-10-14 01:02

import django.core.validators
import game.name_generator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_company_current_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='is_perfectionist',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='morale',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='productivity',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='project',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='salary',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='skill_level',
        ),
        migrations.AddField(
            model_name='employee',
            name='coding_accuracy',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='employee',
            name='coding_speed',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='employee',
            name='debugging',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='employee',
            name='employee_type',
            field=models.CharField(choices=[('PERFECTIONIST', 'Perfectionist'), ('FAST_WORKER', 'Fast Worker')], default='unknown', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='teamwork',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(default=game.name_generator.generate_name, max_length=100),
        ),
    ]
