# Generated by Django 5.1.2 on 2024-10-15 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_employee_project_employee_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='perceived_coding_accuracy',
            field=models.CharField(default='unknown', max_length=20),
        ),
        migrations.AddField(
            model_name='employee',
            name='perceived_coding_speed',
            field=models.CharField(default='unknown', max_length=20),
        ),
        migrations.AddField(
            model_name='employee',
            name='perceived_debugging',
            field=models.CharField(default='unknown', max_length=20),
        ),
        migrations.AddField(
            model_name='employee',
            name='perceived_teamwork',
            field=models.CharField(default='unknown', max_length=20),
        ),
    ]
