# Generated by Django 5.1.2 on 2024-10-15 17:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0013_employee_perceived_coding_accuracy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='morale',
            field=models.IntegerField(default=75, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='employee',
            name='productivity',
            field=models.IntegerField(default=75, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
