# Generated by Django 5.1.2 on 2024-10-16 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0014_employee_morale_employee_productivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='personality_traits_string',
            field=models.TextField(blank=True, default=''),
        ),
    ]
