# Generated by Django 5.1.2 on 2024-10-17 01:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0015_employee_personality_traits_string'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='perceived_personality_traits_string',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='HiringProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_type', models.CharField(max_length=20)),
                ('process_type', models.CharField(max_length=20)),
                ('start_date', models.DateField()),
                ('expected_hire_date', models.DateField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.company')),
                ('employee', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.employee')),
            ],
        ),
    ]
