# Generated by Django 5.1.2 on 2024-10-21 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0016_employee_perceived_personality_traits_string_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='complexity',
            field=models.CharField(choices=[('SHODDY', 'Shoddy'), ('STANDARD', 'Standard Practice'), ('ADVANCED', 'Advanced')], default='STANDARD', max_length=20),
        ),
        migrations.AddField(
            model_name='feature',
            name='is_required',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='project',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='deadline_type',
            field=models.CharField(choices=[('STANDARD', 'Standard'), ('AGGRESSIVE', 'Aggressive'), ('CAUTIOUS', 'Cautious')], default='STANDARD', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('FINTECH', 'Fintech'), ('GAME_DEV', 'Game Development')], default='', max_length=20),
            preserve_default=False,
        ),
    ]
