# Generated by Django 5.1.2 on 2024-10-21 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0017_feature_complexity_feature_is_required_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='deadline_type',
            field=models.CharField(choices=[('standard', 'Standard'), ('aggressive', 'Aggressive'), ('cautious', 'Cautious')], default='standard', max_length=20),
        ),
    ]
